<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AntennaGuardian.Core\AntennaGuardian.Core.csproj" />
    <ProjectReference Include="..\AntennaGuardian.Flex\AntennaGuardian.Flex.csproj" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>AntennaGuardian.App.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>AntennaGuardian</AssemblyName>
    <Version>0.3.2</Version>
    <ApplicationIcon>Assets\AntennaGuardian.ico</ApplicationIcon>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\AntennaGuardian.ico" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <PropertyGroup>
    <StartupObject>AntennaGuardian.App.App</StartupObject>
  </PropertyGroup>

</Project>
